modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/impleri/block-skills/issues"
license = "MIT"

[[mods]]
modId = "blockskills"
version = "${version}"
displayName = "Block Skills"
authors = "impleri"
description = '''
A library mod that exposes KubeJS methods to restrict how players see and interact with blocks.
'''
#logoFile = ""

[[dependencies.blockskills]]
modId = "playerskills"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockskills]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockskills]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockskills]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"
